/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samsungimaging_asphodel_multimedia_FFmpegJNI */

#ifndef _Included_com_samsungimaging_asphodel_multimedia_FFmpegJNI
#define _Included_com_samsungimaging_asphodel_multimedia_FFmpegJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samsungimaging_asphodel_multimedia_FFmpegJNI
 * Method:    ffplayMain
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_samsungimaging_asphodel_multimedia_FFmpegJNI_ffplayMain
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
