/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samsungimaging_asphodel_multimedia_CPUFeaturesJNI */

#ifndef _Included_com_samsungimaging_asphodel_multimedia_CPUFeaturesJNI
#define _Included_com_samsungimaging_asphodel_multimedia_CPUFeaturesJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samsungimaging_asphodel_multimedia_CPUFeaturesJNI
 * Method:    cpufeaturesMain
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_samsungimaging_asphodel_multimedia_CPUFeaturesJNI_cpufeaturesMain
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
